
sudo: required

services:
  - docker

language: python
python:
  - '3.6'
  - '3.7-dev'

matrix:
  allow_failures:
  - python: "3.7-dev"

cache: pip

install: 'pip install -r requirements.txt'

env:
  - DEBUG=True

script:
  - "true"

addons:
  postgresql: '9.6'

after_success:
  - ./deploy/containerize.sh
