resources:
  containers:
  - container: copy36
    image: python:3.6

jobs:
- job: RunInContainer
  pool:
    vmImage: 'ubuntu-latest'

  strategy:
    matrix:
      py36:
        containerResource: copy36

  container: $[ variables['containerResource'] ]

  steps:
    - script: printenv
