# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 11:59
from __future__ import unicode_literals

from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='MasterPage',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meta', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('page_guid', models.CharField(editable=False, max_length=50, verbose_name='Original page GUID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField(editable=False, verbose_name='Original document ID')),
                ('language', models.CharField(max_length=3)),
                ('meta', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('content', models.TextField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.MasterPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
