# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField(editable=False, verbose_name='Original document ID')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='doc',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Page'),
        ),
    ]
