# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20160920_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='page',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='doc_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Original document ID'),
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
