# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20160926_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='doc_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
