# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 14:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20161205_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
