# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_page_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
