# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_page_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Meta field name')),
                ('slug', models.SlugField(verbose_name='Meta field slug')),
                ('pages', models.ManyToManyField(to='info.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
